### DISCUSSION TITLE
How to group temporary worlds together?

### DISCUSSION THREAD

**Discussion by Frerduro** [plan-player-analytics/Plan#2393] [Q&A] [answered]
Add a small option to whitelist the worlds it keeps track of since this can happen after just half a day if you have temporary worlds
![worldcapture](https://user-images.githubusercontent.com/35627247/42983328-f6c813e0-8b9a-11e8-8bed-9a59f77dd18b.PNG)

**Comment by AuroraLS3** [comment, marked as answer]
You can use World Alias settings to group the temporary worlds as a single world

```
World_aliases:
    # -----------------------------------------------------
    # World aliases can be used to rename worlds and to combine multiple worlds into a group.
    # -----------------------------------------------------
    List:
        DXL_Game0: DXL
        DXL_Game1: DXL
```

or

```
World_aliases:
    # -----------------------------------------------------
    # World aliases can be used to rename worlds and to combine multiple worlds into a group.
    # -----------------------------------------------------
    Regex:
      - "DXL:^DXL.*"
```
