### DISCUSSION TITLE
CUSTOM.json

### DISCUSSION THREAD

**Discussion by SlimeDog** [plan-player-analytics/Plan#3383] [Q&A] [answered]
`plugins/Plan/AnalysisResults/locale/CUSTOM.json` seems to have incorrect content on my server -- the wrong web server URL. Where/how is the file content generated?

```
{
  "message": "Language not found, see http://[URL_ELIDED]:8804/v1/locale for available language codes."
}
```

**Comment by AuroraLS3** [comment]
This is generated from /plugins/Plan/locale.txt

I assume you're using export so it's probably a bug in export not excluding this file if the other doesn't exist

**Comment by SlimeDog** [comment]
As you surmise, `plugins/Plan/locale.txt` does not exist.

Am I exporting? Do I want/need to be? I do not remember the purpose of exporting.

Excerpt from `config.yml`
```
Export:
    HTML_Export_path: 'AnalysisResults'
    JSON_Export_path: 'RawJSON'
    Parts:
        # Player pages/JSON are only written on join/leave.
        Player_pages: false
        Player_JSON: false
        Players_page: false
        Server_page: false
        Server_JSON: false
    # All player pages/JSON can be exported by using /plan m export players
    Export_player_on_login_and_logout: false
    # If there are multiple servers the period is divided evenly to avoid export of all servers at once
    # Also affects Players page export
    Server_refresh_period:
        Time: 20
        Unit: MINUTES
```
