### DISCUSSION TITLE
Setting up Plan with Caddy as a reverse proxy

### DISCUSSION THREAD

**Discussion by Metacinnabar** [plan-player-analytics/Plan#3812] [Q&A]
I am currently running Caddy as service with the Caddyfile containing
analytics.domain.net {
    reverse_proxy :8804
}

I am using Plan 5.4 build 1722.1 running on a 1.8.8 Minecraft server with Java 8
This Minecraft server is running on pterodactyl
The pterodactyl server has been allocated both the Minecraft port (25565) and Plan port (8804)

My config looks like this:
```
Webserver:
    Port: 8804
    Alternative_IP: true
        # %port% is replaced automatically with Webserver.Port
        Address: analytics.domain.net
    # InternalIP usually does not need to be changed, only change it if you know what you're doing!
    # 0.0.0.0 allocates Internal (local) IP automatically for the WebServer.
    Internal_IP: 0.0.0.0
    Security:
        SSL_certificate:
            KeyStore_path: proxy
            Key_pass: default
            Store_pass: default
            Alias: alias 
```
    
When going on to analytics.domain.net it doesn't stop trying to load until it times out and shows no information
