### ISSUE TITLE
/network/index.html is not exported

### ISSUE THREAD

**Issue by xXSchrandXx** [plan-player-analytics/Plan#1019]
### Describe the bug

The config options doesn't work:
```YAML
Webserver:
    Disable_Webserver: true
    External_Webserver_address: "https://leaderboard.ragebears.de"
Export:
    Parts:
        Player_pages: true
        Player_JSON: true
        Players_page: true
        Server_page: true
        Server_JSON: true
```

### Server information
**Plan Version:** 4.8.1
**Server:** BungeeCord git:BungeeCord-Bootstrap:1.14-SNAPSHOT:8b5c158:233 (git:BungeeCord-Bootstrap:1.14-SNAPSHOT:8b5c158:233)
**Database:** MySQL

**Operating SubSystem:** Linux (amd64) version 3.16.0-4-amd64
**Java Version:** 1.8.0_191, Oracle Corporation
**Java VM Version:** Java HotSpot(TM) 64-Bit Server VM version 25.191-b12, Oracle Corporation
### Connection Log:

Server Address | Request Type | Response | Sent
-- | -- | -- | --
**No Connections Logged**
### Server:

Server Name | Address 
-- | --
### Benchmarks
```
492572 ns   0 B    Inspect Parse, Fetch
31 ms      +45 MB  Spieler page players table parsing
18020 ns   -87 KB  Source AdvancedBan
3 ms       -827 KB Source LuckPerms
2 ms       +155 MB Source ViaVersion
3 ms       -7 MB   WebServer Initialization
```

### Logged Errors
**No Errors logged.**

### Additional information

The web server runs on the same server as the Minecraft servers. The folder in which the web server works belongs to the same user and has 777 rights.

**Other:**
[Debugpage](http://mc.ragebears.de:8804/debug)
