### ISSUE TITLE
Plan opens a ton of threads which it does not close in bungeecord.

### ISSUE THREAD

**Issue by KarlOfDuty** [plan-player-analytics/Plan#1034]
### Describe the bug
It seems to be opening a new thread about once every 5 seconds. I have attached a thread dump below.

### Server information
Waterfall version 282
Plan version 4.8.1

### Exceptions & Other Logs
[javastack.txt](https://github.com/plan-player-analytics/Plan/files/3158281/javastack.txt)

**Frequency of occurrence**: New threads open once every few seconds.

**Comment by Rsl1122** [comment]
Hmm, this is likely related to delay settings.
Could you send the `Time` section of your Plan config

**Comment by KarlOfDuty** [comment]
Here you go:
```yaml
Time:
    # UTC used if false. Only affects Timestamps and graphs.
    Use_server_timezone: true
    Delays:
        Ping_server_enable_delay: 1
            Unit: HOURS
        Ping_player_join_delay: 1000
            Unit: DAYS
        Wait_for_DB_Transactions_on_disable: 20
            Unit: SECONDS
    Thresholds:
        # How long player needs to be idle until Plan considers them AFK
        AFK_threshold: 3
            Unit: MINUTES
        # Activity Index considers last 3 weeks and uses these thresholds in the calculation
        # The index is a number from 0 to 5.
        # These numbers were calibrated with data of 250 players (Small sample size).
        Activity_index:
            Login_threshold: 2
            Playtime_threshold: 30
                Unit: MINUTES
        Remove_inactive_player_data_after: 180
            Unit: DAYS
    Periodic_tasks:
        Check_DB_for_server_config_files_every: 1
            Unit: MINUTES
        Clean_caches_every: 10
            Unit: MINUTES
        Clean_Database_every: 1
            Unit: HOURS
        Extension_data_refresh_every: 1
            Unit: HOURS
```
