### ISSUE TITLE
[question] Why isnt my Nginx proxy working?

### ISSUE THREAD

**Issue by FrozenBeard** [plan-player-analytics/Plan#1215]
Ahoy!

I finally got around to updating to v5+, Since I recently moved dedicated machines, I thought I would try the internal web-server behind some Nginx basic authentication as a proxy, so I didnt need to have a port and to protect the web UI so its just me that an get to it.
I previously used to export all HTML and just host with Nginx with auth.
I've not even got to the auth yet, my domain & SSL works fine, this is the same setup I have for Dynmap, so I have no idea why its not working.

- I opened the port 8084 in my firewall to test that plan was working fine, it is.
- The nginx web server is definitely setup and working with SSL, I have 2 other sub-domains already working for other projects too.

It reports "502 Bad Gateway", which points to something not being setup properly Nginx side, which is very weird as its exactly the same as my Dynmap proxy setup which works fine.

The idea with the proxy is I can use sub.domain.com without needing to open ports or use a port in the URL.

Nginx Config

```
server {
    server_name  sub.domain.com;

    location / {
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_pass http://localhost:8084;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/sub.domain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/sub.domain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = sub.domain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name  sub.domain.com;

    listen 80;
    return 404; # managed by Certbot
}
```

Plan config
```
Webserver:
    Port: 8804
    Security:
        SSL_certificate:
            Alias: 'alias'
            KeyStore_path: 'SSLCertificate.keystore'
            Key_pass: 'default'
            Store_pass: 'default'
    # InternalIP usually does not need to be changed, only change it if you know what you're doing!
    # 0.0.0.0 allocates Internal (local) IP automatically for the WebServer.
    Internal_IP: 0.0.0.0
    Disable_Webserver: false
    External_Webserver_address: "https://sub.domain.com"
    Alternative_IP: true
        # %port% is replaced automatically with Webserver.Port :%port%
        Address: sub.domain.com
```

Edit: im a retard I typed the port in wrong... but making this post made me re-read everything...
