### ISSUE TITLE
Exception thrown in BungeeCord sometimes when players log in or out

### ISSUE THREAD

**Issue by c0wg0d** [plan-player-analytics/Plan#1352]
### Describe the issue
Exception thrown in BungeeCord sometimes when players log in or out

### Server information
Using Plan Build 415, various Paper versions from 1.12 to 1.15.2

### Exceptions & Other Logs
https://gist.github.com/c0wg0d/89955a5e164237f08fdb6e02779c5cfe

### Additional information
Relevant config section (same across all my servers):
```
Export:
    HTML_Export_path: /minecraft/bungee/plugins/Plan/html
    JSON_Export_path: /minecraft/bungee/plugins/Plan/html/json
    Parts:
        # Player pages/JSON are only written on join/leave.
        Player_pages: true
        Player_JSON: false
        Players_page: true
        Server_page: true
        Server_JSON: false
    # All player pages/JSON can be exported by using /plan m export players
    Export_player_on_login_and_logout: true
    # If there are multiple servers the period is divided evenly to avoid export of all servers at once
    # Also affects Players page export
    Server_refresh_period: 20
        Unit: MINUTES
```
