### ISSUE TITLE
Login and logout urls redirect incorectly when used on a subdirectory with a reverse proxy

### ISSUE THREAD

**Issue by BenjiButton** [plan-player-analytics/Plan#1479]
### Describe the issue
With a reverse proxy in a sub-directory (`/plan/`), the login and logout pages don't work
When a person clicks on the login button when the URL is something like this: `/plan/login?from=/server/` it redirects to `/server/` instead of `/plan/server/` (it works if i manually remove the first `/` after `?from=`), and the logout URL goes to `/auth/logout` instead of `/plan/auth/logout` so it does not log them out

### Additional information
Apache config (inside the https virtual-host block):
```Apache
		ProxyPass /plan/ http://0.0.0.0:8804/
		ProxyPassReverse /plan/ http://0.0.0.0:8804/
```
I'm not entirely sure if it is something wrong with my reverse proxy config or if the error is in plan itself

**Comment by Rsl1122** [comment]
Have you set your Alternative_IP to point to <reverse-proxy>/plan

**Comment by BenjiButton** [comment]
Yes i have, here is the web server config in plan (i just replaced my actual domain with `<domain>`:
```yaml
Webserver:
    Port: 8804
    Alternative_IP: true
        # %port% is replaced automatically with Webserver.Port
        # Address: localhost:%port%
        Address: <domain>/plan
    # InternalIP usually does not need to be changed, only change it if you know what you're doing!
    # 0.0.0.0 allocates Internal (local) IP automatically for the WebServer.
    Internal_IP: 127.0.0.1
    Security:
        SSL_certificate:
            # KeyStore_path: Cert.jks
            KeyStore_path: proxy
            Key_pass: default
            Store_pass: default
            Alias: alias
        # HTTPS is required for Login.
        Disable_authentication: false
        # Cross-Origin Resource Sharing (Requests from non-Plan web pages)
        # https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
        CORS:
            Allow_origin: "*"
    Disable_Webserver: false
    External_Webserver_address: https://<domain>/plan
```
