### ISSUE TITLE
PLAN causing dozens Essentials economy lag error messages

### ISSUE THREAD

**Issue by musicalcomputergeek** [plan-player-analytics/Plan#1543]
### Describe the issue

Restarting the server or reloading PLAN causes Essentials to generate dozes of messages such as:
`[Essentials] Lag Notice - Slow Economy Response - Request took over 7,539.19ms!`

Removing the plan.jar file and restarting the server fixes this issue, but I'd like to be able to use PLAN without this issue occurring. 

I've also tried disabling the Essentials extension (along with several others in attempts to fix) in the config, but this does not fix the issue. Instead it caused PLAN to generate the below errors/logs.

### Server information

Plan v5.1 build 624
CraftBukkit git-Spigot-56f8471-7554e08 (MC: 1.14.4)
Server v1.14.4-R0.1-SNAPSHOT

### Exceptions & Other Logs

```
[Plan] Ran into DBOpException - logged to plugins/Plan/logs/DBOpException-377218d0c0.txt
[Plan] (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
[Plan] What to do: Report and/or disable Essentials extension in the Plan config.
```

**Contents of DBOpException-377218d0c0.txt:**

```
377218d0c0 - Last occurred: 2020-08-02 Occurrences: 2
---- Context 2 ----
Plan v5.1 build 624
CraftBukkit git-Spigot-56f8471-7554e08 (MC: 1.14.4)
Server v1.14.4-R0.1-SNAPSHOT

Report and/or disable Essentials extension in the Plan config.
Essentials
SERVER_EXTENSION_REGISTER
Gathering for server

---- Context 1 ----
Plan v5.1 build 624
CraftBukkit git-Spigot-56f8471-7554e08 (MC: 1.14.4)
Server v1.14.4-R0.1-SNAPSHOT

Report and/or disable Essentials extension in the Plan config.
Essentials
SERVER_EXTENSION_REGISTER
Gathering for server

---- Stacktrace ----
com.djrapitops.plan.exceptions.database.DBOpException: Transaction tried to execute although database is closed.
   com.djrapitops.plan.storage.database.SQLDB.executeTransaction(SQLDB.java:242)
   com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer$Gatherer.gather(ProviderValueGatherer.java:200)
   com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer$Gatherer.gather(ProviderValueGatherer.java:184)
   com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer.updateValues(ProviderValueGatherer.java:161)
   com.djrapitops.plan.extension.ExtensionSvc.updateServerValues(ExtensionSvc.java:210)
   com.djrapitops.plan.extension.ExtensionSvc.lambda$register$0(ExtensionSvc.java:119)
   com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$1(Processing.java:79)
   java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   java.lang.Thread.run(Thread.java:748)
```

**Comment by Rsl1122** [comment]
Try disabling the Vault Economy Extension instead

**Comment by musicalcomputergeek** [comment]
> Try disabling the Vault Economy Extension instead

Both that extension and the Essentials extensions are disabled.

**Comment by Rsl1122** [comment]
Disable the vault extension and enable the essentials extension, as the essentials extension does not gather economy data. This should take care of the lag and stop the error above

**Comment by musicalcomputergeek** [comment]
I'm still getting the Essential Slow Economy Response message. Below is my config:

```
Plugins:
    AdvancedAchievements:
        Enabled: true
    Buycraft:
        Secret: 'asdf'
        Enabled: true
    CoreProtect:
        Enabled: true
    DiscordSRV:
        Enabled: true
    Economy (Essentials Economy):
        Enabled: false
    Economy (Vault):
        Enabled: false
    Essentials:
        Enabled: true
    Jobs:
        Enabled: true
    LuckPerms:
        Enabled: true
    Permission Groups (Vault):
        Enabled: false
    Towny:
        HideTowns:
          - ExampleTown
        Enabled: true
    ViaVersion:
        Enabled: true
    nuVotifier:
        Enabled: false
    Factions:
        HideFactions:
          - ExampleFaction
```
