### ISSUE TITLE
Plan redirecting me to wrong URL address

### ISSUE THREAD

**Issue by iBars** [plan-player-analytics/Plan#1768]
### Describe the issue
After updating from Plan `v5.1-497` to `v5.1-813` I can't open panel in browser. I used nginx as proxy to use my domain and SSL, so I proxying `plan.site.com` to `http://127.0.0.1:8804`. But it redirecting me (since Plan update) to router internal address `http://10.10.10.9:8804/login?`.

My Plan config (on BungeeCord):

```
Webserver:
    Port: 8804
    Alternative_IP: true
        # %port% is replaced automatically with Webserver.Port
        Address: plan.site.com
    # InternalIP usually does not need to be changed, only change it if you know what you're doing!
    # 0.0.0.0 allocates Internal (local) IP automatically for the WebServer.
    Internal_IP: 127.0.0.1
```

My nginx site config:

```
server {
	listen       443 ssl http2;
	server_name  plan.site.com;

	# ssl on; # Deprecated
	ssl_certificate C:/path/to/_SSL_/site.com.crt;
	ssl_certificate_key C:/path/to/_SSL_/site.com.key;

	# Передаем запрос Plan
	location / {
		proxy_pass http://127.0.0.1:8804;
		proxy_redirect     off;

		auth_basic "Administrator Login";
		auth_basic_user_file C:/path/to/nginx/conf/.htpasswd;

		proxy_set_header   Host             $host;
		proxy_set_header   X-Real-IP        $remote_addr;
		proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
		proxy_set_header   X-Forwarded-Proto $scheme;
		#set_real_ip_from   10.10.10.9;
		real_ip_header     X-Forwarded-For;
		#real_ip_header     X-Real-IP;
		real_ip_recursive  on;

		# Максимальный размер тела запроса клиента
		client_max_body_size       10m;
		client_body_buffer_size    128k;
		#client_body_temp_path     tmp/client_body_temp;

		proxy_connect_timeout      90;
		proxy_send_timeout         90;
		proxy_read_timeout         90;

		proxy_buffer_size          4k;
		proxy_buffers              4 32k;
		proxy_busy_buffers_size    64k;
		proxy_temp_file_write_size 64k;
		#proxy_temp_path           tmp/proxy_temp;

		charset  utf8;
	}

	if_modified_since off;
	#access_log off;
	#error_log off;
}

```

### Server information
Server version is BungeeCord for MC 1.15.2.
Plan version specified above (5.1-813).
