### ISSUE TITLE
Warm up specific placeholders upon player join

### ISSUE THREAD

**Issue by AuroraLS3** [plan-player-analytics/Plan#1909]
### Is your feature request related to a problem? Please describe.

Users find the current placeholder system confusing when plugins are using server-thread for placeholder replacement.

### I would like to be able to..

It is possible to improve this experience by providing a section in the Plan config to specify which placeholders are in use, so that they can be fetched to the cache when a player joins.

```yml
Plugins:
    PlaceholderAPI:
        Load_these_placeholders_on_join:
             - %plan_example_placeholder%
```
