### ISSUE TITLE
Slow web page response for charts

### ISSUE THREAD

**Issue by SlimeDog** [plan-player-analytics/Plan#2135]
### Describe the issue

Server -- all software up-to-date:
```
CentOS Linux release 7.9.2009
SQLite 3.7.17 -- database: 31MB
Spigot 1.17.1-3262
Plan 5.4 build 1463
```
Client -- all software up-to-date:
```
MacOS Big Sur 11.6 
Safari 15.0 or Firefox 93.0
```

I usually test Plan development builds when new versions are released, but I did not test b1463 until today. I deleted the Plan libraries and restarted the server to regenerate the latest library versions:
```
libraries/com/google/code/gson/gson/2.8.6/gson-2.8.6.jar
libraries/com/google/protobuf/protobuf-java/3.11.4/protobuf-java-3.11.4.jar
libraries/com/google/protobuf/protobuf-java/3.11.4/relocated/Plan/protobuf-java-3.11.4.jar
libraries/me/lucko/jar-relocator/1.4/jar-relocator-1.4.jar
libraries/org/ow2/asm/asm/9.1/asm-9.1.jar
libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar
libraries/org/xerial/sqlite-jdbc/3.36.0.3/sqlite-jdbc-3.36.0.3.jar
libraries/org/xerial/sqlite-jdbc/3.36.0.3/relocated/Plan/sqlite-jdbc-3.36.0.3.jar
libraries/mysql/mysql-connector-java/8.0.26/mysql-connector-java-8.0.26.jar
libraries/mysql/mysql-connector-java/8.0.26/relocated/Plan/mysql-connector-java-8.0.26.jar
```
(note that `plan reload` does not regenerate missing libraries, and I do not see a separate subcommand to do so).

My standard test is the TPS performance chart. It took 8 minutes to load partially
![Screen Shot 2021-10-18 at 11 26 28 AM](https://user-images.githubusercontent.com/17748923/137788834-f511c8e6-bf2a-4c17-a2a2-2300a2db5964.png)
13 minutes to load fully (visually)
![Screen Shot 2021-10-18 at 11 30 49 AM](https://user-images.githubusercontent.com/17748923/137789070-17274cef-67f8-4e35-b67b-727d65ccc4a8.png)
and 18 minutes for the page to respond to clicks. The same issue occurs with both Safari and Firefox (tested serially, so as to not create database or client interference).

### Exceptions & other logs

```text
No log errors or other output.
```

### Plugin versions

None.

### Additional information

```
Plugin:
    Logging:
        # More information about Locale
        # https://github.com/plan-player-analytics/Plan/wiki/Localization
        Locale: default
        Create_new_locale_file_on_next_enable: false
        Dev: false
        Delete_logs_after_days: 2
    Update_notifications:
        # Display update notification on the website
        Check_for_updates: false
        Notify_about_DEV_releases: false
    Configuration:
        Allow_proxy_to_manage_settings: false
# -----------------------------------------------------
# Supported databases: SQLite, MySQL
# -----------------------------------------------------
Database:
    Type: SQLite
    MySQL:
        Host: localhost
        Port: 3306
        User: root
        Password: minecraft
        Database: Plan
        # Launch options to append after mysql driver address
        Launch_options: "?rewriteBatchedStatements=true&useSSL=false&serverTimezone=UTC"
        Max_connections: 8
```
