### ISSUE TITLE
web server doesn't works

### ISSUE THREAD

**Issue by Timtaran** [plan-player-analytics/Plan#2422]
### Describe the issue
I have 1 proxy(velocity) and 2 servers(paper), I disable web servers of plan at 2 servers and enable it at velocity, web server doesn't works.
![изображение](https://user-images.githubusercontent.com/60805088/173173773-f7650c16-8a10-4730-8434-3dc119c765c2.png)
config:
```yml
Webserver:
    Port: 25566
    Alternative_IP: false
        # %port% is replaced automatically with Webserver.Port
        Address: your.domain.here:%port%
    # InternalIP usually does not need to be changed, only change it if you know what you're doing!
    # 0.0.0.0 allocates Internal (local) IP automatically for the WebServer.
    Internal_IP: 0.0.0.0
    Cache:
        Reduced_refresh_barrier: 15
            Unit: SECONDS
        Invalidate_query_results_on_disk_after: 7
            Unit: DAYS
        Invalidate_disk_cache_after: 2
            Unit: DAYS
        Invalidate_memory_cache_after: 5
            Unit: MINUTES
    Security:
        SSL_certificate:
            KeyStore_path: Cert.jks
            Key_pass: default
            Store_pass: default
            Alias: alias
        # HTTPS is required for Login.
        Disable_authentication: false
        # Cross-Origin Resource Sharing (Requests from non-Plan web pages)
        # https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
        CORS:
            Allow_origin: "*"
        # Allows using the whitelist & brute-force shield with a reverse-proxy.
        # ! Make sure non-proxy access is not possible, it would allow IP spoofing !
        Use_X-Forwarded-For_Header: false
        IP_whitelist: false
            Whitelist:
              - "192.168.0.0"
              - "0:0:0:0:0:0:0:1"
        # Does not affect existing cookies
        Cookies_expire_after: 2
            Unit: HOURS
    Disable_Webserver: false
    External_Webserver_address: "https://www.example.address"
```
### Plugin versions
1690
