### ISSUE TITLE
Alternative IP only match with http

### ISSUE THREAD

**Issue by DaniGTA** [plan-player-analytics/Plan#3032]
### Describe the issue
Webbrowser error:

Configured address http://test.de/mc/stats did not match start of https://test.de/mc/stats/server/Server%201, falling back to relative address. Configure 'Webserver.Alternative_IP' settings to point to your address.

### Exceptions & Other Logs
```
Webserver:
    Port: 8804
    Alternative_IP:
        # %port% is replaced automatically with Webserver.Port
        Address: test.de/mc/stats
        Enabled: true
```

### Plugin versions
5.5 build 2391
