### ISSUE TITLE
Setting player activity as a rank/sync with DiscordSRV

### ISSUE THREAD

**Issue by TomLewis** [plan-player-analytics/Plan#3208]
### I would like to be able to..

Ahoy!

# Activity as Group/rank & Discord role

I would like to be able to have roles on my discord server that are 1:1 copies of player activity on Plan.

DiscordSRV can sync ranks, so it could be as simple as manually creating ranks in Luckperms and then having Plan set the rank when they log in to their Activity status, this could be a simple array in the plan configs, for example "Very Active = VeryActiveRank" then in the DiscordSRV settings have that rank sync to a discord role.

# Reasoning
This would provide fantastic insight into the activity of a player if they are ranting or posting on a discord which is seperate from in-game, for example servers with a lot of players will still have hundreads of peolpe in the discord that no longer play on the server!

### Is your feature request related to a problem? Please describe.

1. Ex-players or inactive players would be shown as a muted grey color so people understand their views may be outdated as they no longer play.
2. Being able to limit discord channels based on activity, for exmaple suggestions channel could be for Very Active players only

# Considered Options
You have an activity placeholder, I was going to just try and script this in commandhelper, that when players log in, it grabs their Activity and sets them at the correct LP group  if its changed, BUT I cant get the placeholder to display the first time its used, I tested it in chat and it takes a few times of spamming it to actually pull the activity of a player, otherwise it just displays as the placeholder text.

I have set `%player_activity_group%` in `Load_these_placeholders_on_join` with no change in having to spam it to work. Via https://github.com/plan-player-analytics/Plan/wiki/PlaceholderAPI

```
    PlaceholderAPI:
        Tracked_player_placeholders:
          - %example_placeholder%
        Enabled: true
        Load_these_placeholders_on_join:
          - %plan_server_uuid%
          - %player_activity_group%
```
