### ISSUE TITLE
Bug since recent update : Illegal pattern character 'A'

### ISSUE THREAD

**Issue by Athar42** [plan-player-analytics/Plan#3658]
### Describe the issue
Since I updated to latest Velocity 3.3.0-SNAPSHOT-396 and Plan 2883, I can't use it anymore, I always get this error below

### Exceptions & Other Logs
```
f4f0932ee9 - Last occurred: 2024-06-04 Occurrences: 2
---- Context 2 ----
Plan v5.6 build 2883
Velocity 3.3.0-SNAPSHOT (git-07f1f9e7-b396)
Server v3.3.0-SNAPSHOT (git-07f1f9e7-b396)


---- Context 1 ----
Plan v5.6 build 2883
Velocity 3.3.0-SNAPSHOT (git-07f1f9e7-b396)
Server v3.3.0-SNAPSHOT (git-07f1f9e7-b396)


---- Stacktrace ----
java.lang.IllegalStateException: java.lang.IllegalArgumentException: Illegal pattern character 'A'
   com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$3(Processing.java:113)
   java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
   java.base/java.lang.Thread.run(Thread.java:1583)
Caused by:
java.lang.IllegalArgumentException: Illegal pattern character 'A'
   java.base/java.text.SimpleDateFormat.compile(SimpleDateFormat.java:849)
   java.base/java.text.SimpleDateFormat.initialize(SimpleDateFormat.java:657)
   java.base/java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:628)
   com.djrapitops.plan.delivery.formatting.time.DateFormatter.format(DateFormatter.java:59)
   com.djrapitops.plan.delivery.formatting.time.DateFormatter.format(DateFormatter.java:55)
   com.djrapitops.plan.delivery.formatting.time.DateFormatter.format(DateFormatter.java:50)
   com.djrapitops.plan.delivery.formatting.time.YearFormatter.format(YearFormatter.java:45)
   com.djrapitops.plan.delivery.formatting.time.YearFormatter.apply(YearFormatter.java:36)
   com.djrapitops.plan.delivery.formatting.time.YearFormatter.apply(YearFormatter.java:28)
   com.djrapitops.plan.delivery.webserver.cache.JSONFileStorage.addMissingTimestamp(JSONFileStorage.java:122)
   com.djrapitops.plan.delivery.webserver.cache.JSONFileStorage.storeJson(JSONFileStorage.java:93)
   com.djrapitops.plan.delivery.webserver.cache.JSONMemoryStorageShim.storeJson(JSONMemoryStorageShim.java:51)
   com.djrapitops.plan.delivery.webserver.cache.JSONStorage.storeJson(JSONStorage.java:41)
   com.djrapitops.plan.delivery.webserver.cache.JSONStorage.storeJson(JSONStorage.java:46)
   com.djrapitops.plan.delivery.webserver.cache.AsyncJSONResolverService.lambda$submitToProcessing$2(AsyncJSONResolverService.java:157)
   com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$3(Processing.java:111)
   java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
   java.base/java.lang.Thread.run(Thread.java:1583)

```

### Plugin versions
Plan v5.6 build 2883
Velocity 3.3.0-SNAPSHOT (git-07f1f9e7-b396)

### Additional information
Not for now :)

Thank you for your assistance

**Comment by AuroraLS3** [comment]
Could you send the Formatting section of the Plan config where this is occurring - there seems to be an incompatible pattern in there for some Date formatting setting

**Comment by Athar42** [comment]
Sure, here it is (from the Velocity proxy) :
```
# -----------------------------------------------------
Formatting:
    Decimal_points: '#.##'
    Time_amount:
        Year: '1 year, '
        Years: '%years% years, '
        Month: '1 month, '
        Months: '%months% months, '
        Day: '1d '
        Days: '%days%d '
        Hours: '%hours%h '
        Minutes: '%minutes%m '
        Seconds: '%seconds%s'
        Zero: '0s'
    # Dates settings use Java SimpleDateFormat.
    # You can find the patterns & examples here:
    # https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
    Dates:
        # Show_recent_day_names replaces day number with Today, Yesterday, Wednesday etc.
        Show_recent_day_names: true
        # Non-regex pattern to replace
        Show_recent_day_names_date_pattern: 'd MMM YYYY'
        Full: 'd MMM YYYY, HH:mm:ss'
        NoSeconds: 'd MMM YYYY, HH:mm'
        JustClock: 'HH:mm:ss'
        # TimeZone Option uses format 'GMT+2' or 'GMT-04:30'
        # Other valid options are 'server' and 'UTC'
        TimeZone: 'server'
# -----------------------------------------------------
```
