### ISSUE TITLE
When using a apache reverse proxy with a subdirectory, it does not display correctly.

### ISSUE THREAD

**Issue by paimonian** [plan-player-analytics/Plan#3902]
config.yml
```
Webserver:
  Port: 8804
  Alternative_IP:
    Enabled: true
    Address: address.com/plan/
```
Apache config (SSL):
```
RewriteEngine on
RewriteRule ^(.*/[^./]+)$ $1/ [R=301,L]
<IfModule mod_proxy.c>
  ProxyRequests Off
  ProxyPass /plan http://localhost:8804
  ProxyPassReverse /plan http://localhost:8804
</IfModule>
```

Logos, etc. will not be displayed correctly, but other data will be displayed.
![2024-12-25 (1)](https://github.com/user-attachments/assets/7e37d83d-b5d0-4bab-beb5-f7d25abf8913)

### Plugin versions
5.6 build 2883
